-- Companies
CREATE TABLE COMPANIES (
    COMPANY_CODE VARCHAR(2) NOT NULL PRIMARY KEY,
    COMPANY_NAME VARCHAR(150) NOT NULL,
    REP_NAME VARCHAR(100) NOT NULL,
    REP_POSITION VARCHAR(50),
    ADDRESS VARCHAR(50),
    CITY_NAME VARCHAR(50),
    USER_CODE VARCHAR(30) NOT NULL,
    LAST_UPDATE DATE,
    REP_RUC VARCHAR(25) NOT NULL,
    STATUS BIT,
    EMAIL VARCHAR(50)
);

-- Users
CREATE TABLE USERS (
    USER_CODE VARCHAR(25) NOT NULL PRIMARY KEY,
    COMPANY_CODE VARCHAR(20) NOT NULL,
    USER_TYPE VARCHAR(20),
    PASSWORD VARCHAR(150) NOT NULL,
    USER_NAME VARCHAR(100) NOT NULL,
    DATE_JOINED DATE,
    EXPIRY_DATE DATE,
    STATUS BIT,
    EMAIL VARCHAR(50),
    FOREIGN KEY (COMPANY_CODE) REFERENCES COMPANIES(COMPANY_CODE)
);

-- Employees
CREATE TABLE EMPLOYEES (
    EMPLOYEE_CODE VARCHAR(25) NOT NULL PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(200) NOT NULL,
    EMPLOYEE_ADDRESS VARCHAR(2),
    EMPLOYEE_PHONE VARCHAR(150) NOT NULL,
    USER_CODE VARCHAR(100) NOT NULL,
    LAST_UPDATE DATE,
    FOREIGN KEY (USER_CODE) REFERENCES USERS(USER_CODE)
);

-- Article Classes
CREATE TABLE ARTICLE_CLASSES (
    CLASS_CODE VARCHAR(20) NOT NULL PRIMARY KEY,
    CLASS_NAME VARCHAR(150) NOT NULL,
    USER_CODE VARCHAR(25) NOT NULL,
    LAST_UPDATE DATE,
    FOREIGN KEY (USER_CODE) REFERENCES USERS(USER_CODE)
);

-- Tax (IVA) for Articles
CREATE TABLE ARTICLE_TAXES (
    TAX_CODE VARCHAR(10) NOT NULL PRIMARY KEY,
    TAX_NAME VARCHAR(60) NOT NULL,
    TAX_PERCENTAGE NUMERIC(25) NOT NULL,
    USER_CODE VARCHAR(25) NOT NULL,
    LAST_UPDATE DATE,
    FOREIGN KEY (USER_CODE) REFERENCES USERS(USER_CODE)
);

-- Units of Measurement
CREATE TABLE ARTICLE_UNITS (
    UNIT_CODE VARCHAR(10) NOT NULL PRIMARY KEY,
    UNIT_NAME VARCHAR(60) NOT NULL,
    USER_CODE VARCHAR(25) NOT NULL,
    LAST_UPDATE DATE,
    FOREIGN KEY (USER_CODE) REFERENCES USERS(USER_CODE)
);

-- Articles / Products
CREATE TABLE ARTICLES (
    ARTICLE_CODE VARCHAR(10) NOT NULL PRIMARY KEY,
    ARTICLE_NAME VARCHAR(60) NOT NULL,
    CLASS_CODE VARCHAR(20) NOT NULL,
    UNIT_CODE VARCHAR(10) NOT NULL,
    CURRENT_STOCK NUMERIC(20, 4),
    COST_PRICE NUMERIC(20, 4),
    LAST_COST NUMERIC(20, 4),
    COST_FLAG BIT,
    FOREIGN KEY (CLASS_CODE) REFERENCES ARTICLE_CLASSES(CLASS_CODE),
    FOREIGN KEY (UNIT_CODE) REFERENCES ARTICLE_UNITS(UNIT_CODE)
);

-- Transaction Types
CREATE TABLE TRANSACTION_TYPES (
    TRANS_CODE VARCHAR(10) NOT NULL PRIMARY KEY,
    TRANS_NAME VARCHAR(60) NOT NULL,
    SIGN CHAR(1)
);

-- Inventory Ledger (Kardex)
CREATE TABLE INVENTORY_LEDGER (
    ARTICLE_CODE VARCHAR(10) NOT NULL,
    ARTICLE_NAME VARCHAR(150) NOT NULL,
    CLASS_CODE VARCHAR(20) NOT NULL,
    UNIT_CODE VARCHAR(10) NOT NULL,
    CURRENT_STOCK NUMBER(20, 4),
    COST_PRICE NUMBER(20, 4),
    LAST_COST NUMBER(20, 4),
    UNIT_COST NUMBER(20, 2),
    COST_FLAG BIT,
    PRIMARY KEY (ARTICLE_CODE, CLASS_CODE, UNIT_CODE),
    FOREIGN KEY (ARTICLE_CODE) REFERENCES ARTICLES(ARTICLE_CODE),
    FOREIGN KEY (CLASS_CODE) REFERENCES ARTICLE_CLASSES(CLASS_CODE),
    FOREIGN KEY (UNIT_CODE) REFERENCES ARTICLE_UNITS(UNIT_CODE)
);
